### POST Create new Library
POST http://localhost:8080/api/libraries
Content-Type: application/json

{
  "library_name": "stltestlib2",
  "library_path": "/home/{{user_folder}}/stltestlib"
}
###

### GET get all Libraries
GET http://localhost:8080/api/libraries

### GET get Library by Id
GET http://localhost:8080/api/libraries/{{library_id}}
